version: "3.8"

services:
  postgres:
    container_name: postgres
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      KEYCLOAK_HOSTNAME: keycloak
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  eureka:
    container_name: eureka
    image: eureka-img
    ports:
      - "8761:8761"
    depends_on:
      - keycloak

  service1:
    container_name: service1
    image: service1-img
    ports:
      - "8082:8082"
    depends_on:
      - eureka

  service2:
    image: service2-img
    container_name: service2
    ports:
      - "8081:8081"
    depends_on:
      - eureka